# 코드 루트 경로
code_root: /home/cathyjeon/ALL_EnTrans_MODEL/EnTrans       # 변경 필수

# 데이터 루트 경로
clarity_data_root: /scratch/CPC_data/CPC3/clarity_CPC3_data

# whisper feature 경로
feature_root: /scratch/CPC_data/CPC3/clarity_CPC3_data/whisper

# 위스퍼 모델 저장 경로
model_whisper_root: ${code_root}/model_whisper
model_L_whisper_root: ${code_root}/model_whisper_L
model_R_whisper_root: ${code_root}/model_whisper_R

# 최종 모델 저장 경로
model_final_LR_root: ${code_root}/model_final_LR

# 예측 파일 저장 경로
dev_predict_file: ${code_root}/result/dev_predict.csv
demo_train_predict_file: ${code_root}/result/demo_train_predict.csv
demo_train_eval_file: ${code_root}/result/demo_train_predict.jsonl

# 데이터들 경로
dataset: clarity_demo_data          # 테스트용
split: train

aug_dataset: ${clarity_data_root}/clarity_data/aug
aug_signals: signals

train_dataset: ${clarity_data_root}/clarity_data/train
train_metadata: ${clarity_data_root}/clarity_data/metadata/CPC3.train_sharp.json
train_references: references
train_signals: signals

dev_dataset: ${clarity_data_root}/clarity_data/dev
dev_metadata: ${clarity_data_root}/clarity_data/metadata/CPC3.dev.json
dev_references: references
dev_signals: signals

demo_train_dataset: ${clarity_data_root}/clarity_demo_data/train
demo_train_metadata: ${clarity_data_root}/clarity_demo_data/metadata/CPC3.train.json
demo_train_references: references
demo_train_signals: signals

# 모델 설정들
sample_rate: 16000
n_fft: 400
n_mels: 80

# 로그 남길 경로
hydra:
  run:
    dir: ${code_root}/log
  job:
    chdir: True
